name: PR Validation

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  # Reuse existing comprehensive test suite
  test:
    uses: ./.github/workflows/test.yml

  # Simple PR validation
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check PR is not empty
        run: |
          if [[ -z "${{ github.event.pull_request.title }}" ]]; then
            echo "❌ PR title cannot be empty"
            exit 1
          fi
          echo "✅ PR validation passed"

      - name: Check for large files
        run: |
          # Prevent accidentally committing large binaries
          if find . -type f -size +10M -not -path "./target/*" -not -path "./.git/*"; then
            echo "⚠️ Large files detected (>10MB)"
            echo "Consider using Git LFS or exclude from repository"
          fi
